server:
  port: ${APP_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/transactions-processor}
    representation:
      uuid: standard
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_JWT_ISSUER_URI:http://localhost:8081/realms/transactions-processor}

import:
  async:
    core-pool-size: ${IMPORT_ASYNC_CORE_POOL_SIZE:2}
    max-pool-size: ${IMPORT_ASYNC_MAX_POOL_SIZE:4}
    queue-capacity: ${IMPORT_ASYNC_QUEUE_CAPACITY:50}
    thread-name-prefix: ${IMPORT_ASYNC_THREAD_NAME_PREFIX:import-}